# Generated by Django 4.1.2 on 2023-01-01 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, choices=[('advertisement', 'advertisement'), ('resume', 'resume'), ('youtube', 'youTube'), ('websites', 'websites'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('others', 'others')], max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='images/cover-images/')),
                ('description', models.TextField(blank=True, default='', max_length=4000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('fileType', models.CharField(choices=[('.psd (photoshop)', '.psd (photoshop)'), ('.ai (illustrator)', '.ai (illustrator)'), ('.fig (figma)', '.fig (figma)'), ('.zip (zip file)', '.zip (zip file)'), ('.aep (after effects)', '.aep (after effects)'), ('stock photos', 'stock photos'), ('others', 'others')], max_length=200)),
                ('trending', models.BooleanField(blank=True, default=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('orderedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Successfull', 'Successfull'), ('Failed', 'Failed')], default='In progress', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('profileImage', models.ImageField(default='images/user-profiles/default-profile.png', upload_to='images/user-profiles/')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='base.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='content_like', to='base.profile'),
        ),
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
    ]
