# Generated by Django 4.1.2 on 2022-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_profile_image_profile_profileimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
