# Generated by Django 4.1.2 on 2022-12-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_content_contenttype_alter_content_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='contentType',
        ),
    ]
