# Generated by Django 4.1.2 on 2022-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_content_contenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='fileType',
            field=models.CharField(choices=[('photoshop', '.psd (photoshop)'), ('adobe illustrator', '.ai (illustrator)'), ('figma', '.fig (figma)'), ('stock-photos', '(.zip) stock photos'), ('after effects', '.aep (after effects)'), ('others', 'others')], max_length=200),
        ),
    ]
