# Generated by Django 4.1.2 on 2022-12-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_content_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockphotoitem',
            name='owner',
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.CharField(blank=True, choices=[('advertisement', 'advertisement'), ('resume', 'resume'), ('youtube', 'youTube'), ('websites', 'websites'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('others', 'others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='fileType',
            field=models.CharField(choices=[('.psd (photoshop)', '.psd (photoshop)'), ('.ai (illustrator)', '.ai (illustrator)'), ('.fig (figma)', '.fig (figma)'), ('.zip (zip file)', '.zip (zip file)'), ('.aep (after effects)', '.aep (after effects)'), ('stock photos', 'stock photos'), ('others', 'others')], max_length=200),
        ),
        migrations.DeleteModel(
            name='PhotoshopItem',
        ),
        migrations.DeleteModel(
            name='StockPhotoItem',
        ),
    ]
