# Generated by Django 4.1.2 on 2022-12-05 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_stockphotoitem_owner_alter_content_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
