# Generated by Django 4.1.2 on 2022-12-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_content_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='trending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
