# Generated by Django 4.1.2 on 2022-12-09 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_content_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('orderedAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Successfull', 'Successfull'), ('Failed', 'Failed')], max_length=200, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
                ('orderItems', models.ManyToManyField(blank=True, related_name='order_items', to='base.content')),
            ],
        ),
    ]
