# Generated by Django 4.1.2 on 2022-12-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Successfull', 'Successfull'), ('Failed', 'Failed')], default='In progress', max_length=200, null=True),
        ),
    ]
