# Generated by Django 4.1.2 on 2022-12-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/cover-images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='images/user-profiles/default-profile.png', upload_to='images/user-profiles/'),
        ),
    ]
