# Generated by Django 4.1.2 on 2022-12-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_content_shortdescription_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4000, null=True),
        ),
    ]
